version: "3.7"

services:
  azuki:
    image: azuki
    build:
      context: .
    ports:
      - 127.0.0.1:9090:9090
    environment:
      - SYLMS_POSTGRES_DB=sylms
      - SYLMS_POSTGRES_USER=sylms
      - SYLMS_POSTGRES_PASSWORD=sylms
      - SYLMS_POSTGRES_HOST=db
      - SYLMS_POSTGRES_PORT=5432
      - SYLMS_PORT=9090
    entrypoint: dockerize --wait tcp://db:5432
    command: /app/azuki
    depends_on:
      - db
  db:
    image: postgres:12.7-alpine
    ports:
      - 127.0.0.1:5432:5432
    environment:
      TZ: Asia/Tokyo
      POSTGRES_DB: sylms
      POSTGRES_USER: sylms
      POSTGRES_PASSWORD: sylms
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
